### ISSUE TITLE
Proform TdF bike errors

### ISSUE THREAD

**Issue by jimmryan1** [cagnulein/QZCompanionNordictrackTreadmill#26]
Robert, here are the logs from the bike after I was seeing the companion app failure messages. 
[2023-01-04_logs.txt](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/10342108/2023-01-04_logs.txt)
[2023-01-03_logs.txt](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/10342109/2023-01-03_logs.txt)
[2023-1-4___0-42_23.txt](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/10342110/2023-1-4___0-42_23.txt)
[2023-1-4___0-30_59.txt](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/10342111/2023-1-4___0-30_59.txt)

**Comment by cagnulein** [comment]
found the issue @jimmryan1 

```
W/OooO00o ( 3663): Android Keystore requires at least Android M
W/OooO00o ( 3663): keyset not found, will generate a new one
W/OooO00o ( 3663): java.io.FileNotFoundException: can't read keyset; the pref value __androidx_security_crypto_encrypted_file_keyset__ does not exist
```

let me fix this right now!

**Comment by cagnulein** [comment]
@jimmryan1 try this https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/tag/3.1.0

**Comment by jimmryan1** [comment]
Still having the same error message, logs have some different failures related to the keystore.
[2023-1-4___7-54_58.txt](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/10344778/2023-1-4___7-54_58.txt)
[2023-1-4___7-48_52.txt](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/10344779/2023-1-4___7-48_52.txt)
[2023-01-04_logs (3).txt](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/10344780/2023-01-04_logs.3.txt)

**Comment by cagnulein** [comment]
the fact is that i can't find any trace of qz at all in these logs

anyway i will try to follow another lead

i will let you know @jimmryan1 
thanks

**Comment by cagnulein** [comment]
@jimmryan1 which android version does the bike have?

**Comment by cagnulein** [comment]
found the error if it's android 5 or lower

```
 java.lang.NoSuchMethodError: No virtual method setExactAndAllowWhileIdle(IJLandroid/app/PendingIntent;)V in class Landroid/app/AlarmManager; or its super classes (declaration of 'android.app.AlarmManager' appears in /system/framework/framework.jar)
        at org.cagnulein.qzcompanionnordictracktreadmill.AlarmReceiver.setAlarm(AlarmReceiver.java:27)
        at org.cagnulein.qzcompanionnordictracktreadmill.MainActivity.onCreate(MainActivity.java:214)
```

**Comment by cagnulein** [comment]
done @jimmryan1  https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/tag/3.1.1

**Comment by jimmryan1** [comment]
It was version 5.1.1 android. That allowed the app to start - I now get this screen. 
![16728482132011050115574409598991](https://user-images.githubusercontent.com/36770322/210597455-3141680f-6c76-4259-be79-de0b5dbd2561.jpg)
I still see all 0s on the primary app, but to get the bike talking now is there anything more I need to do besides putting the IP address under Bike options>proform>ip address and companion ip address?

**Comment by cagnulein** [comment]
ok great!
now clear the proform ip setting and press ok and then put the ip in the nordictrack 2950 ip and press ok and restart qz

Let me know!
In the next days i will be traveling so i will busy :)

**Comment by jimmryan1** [comment]
So far no luck - it stays at 0's. I'm wondering if its actually connecting to the bike/companion app.

**Comment by cagnulein** [comment]
@jimmryan1 ok use the adb logcat button to share a log from the companion e also a debug log from qz

https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

i'm going to sleep soon but i will check in the next days

**Comment by jimmryan1** [comment]
Here is the debug log from the qz app, I'll add the bike log after my meetings this afternoon. Rest well, and no rush on this.
[debug-Wed_Jan_4_14_50_04_2023.log](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/10347428/debug-Wed_Jan_4_14_50_04_2023.log)

**Comment by jimmryan1** [comment]
Here are the logs from the bike. 
[2023-01-04_logs.txt](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/10349499/2023-01-04_logs.txt)
[2023-1-4___23-6_13.txt](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/10349505/2023-1-4___23-6_13.txt)

**Comment by cagnulein** [comment]
@jimmryan1 thanks, i checked the log, and the main issue seems to be the fact that QZ companion app was not running at all. did you try to ride keeping the qz companion on foreground? It's just a guess because the QZ companion seems stopped at all. Let me know!

**Comment by cagnulein** [comment]
@jimmryan1 it's working for sure, we managed to make it work for other android 5 tablet. if you want we can continue
